xvitaly/tuned-switcher

- src/lib/tunedmanager/tunedmanager.cpp
- src/lib/tunedmanager/tunedmanager.h
- src/lib/tunedtypes/tunedtypes.cpp
- src/lib/tunedtypes/tunedtypes.h
- src/tray/trayicon/trayicon.cpp
- src/tray/trayicon/trayicon.h
This adds "Auto profile" item to tray menu for enabling automatic profile selection by Tuned (the automatic profile is almost always "balanced").
> Implement auto profile indication/selection

- .github/workflows/flatpak.yml
- .gitignore
- packaging/flatpak/org.easycoding.TunedSwitcher.yml
Please note that the `gasinvein/action-flatpak-build` action is a subject to change and will likely migrate to another owner/org.
> Add github workflow to build flatpak

- README.md
- assets/metainfo/tuned-switcher.metainfo.xml.in
Updated metainfo sections names.
> Updated metainfo sections names

- src/app/main.cpp
Switched to qEnvironmentVariableIsSet() for checking if ENV is set.
> Switched to qEnvironmentVariableIsSet() for checking if ENV is set

- assets/CMakeLists.txt
> Install documentaion

- .github/workflows/codeql.yml
- README.md
> CodeQL integration

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- .github/ISSUE_TEMPLATE/question.yml
- .gitignore
- .reuse/dep5
- assets/metainfo/tuned-switcher.metainfo.xml.in
- cmake/FindPandoc.cmake
> Licensing fixes

- .github/workflows/linux.yml
Metainfo and desktop files check.
> Metainfo and desktop files check

- .github/workflows/flatpak.yml
Switched freedesktopsdk to version 21.08.
> Switched freedesktopsdk to version 21.08

- .github/workflows/linux.yml
> CI build optimizations

- .github/workflows/codeql.yml
- assets/CMakeLists.txt
- cmake/FindQt.cmake
- docs/generic-installation.md
- src/app/CMakeLists.txt
- src/lib/CMakeLists.txt
- src/lib/notificationsmanager/dbusconverters.h
- src/lib/notificationsmanager/notificationsmanager.cpp
- src/lib/translationmanager/translationmanager.cpp
> Qt 6 compatibility

- .github/workflows/codeql.yml
- .github/workflows/linux.yml
- src/lib/translationmanager/translationmanager.cpp
- src/lib/translationmanager/translationmanager.h
> Enhanced Qt 6 support

- .github/workflows/codeql.yml
- .github/workflows/flatpak.yml
- .github/workflows/linux.yml
CI workflows upgrade. Closes #53.
> CI workflows upgrade

- .github/dependabot.yml
Added dependabot support for tracking GitHub actions updates.
> Added dependabot support for tracking GitHub actions updates

- src/lib/tunedmanager/tunedmanager.cpp
- src/lib/tunedmanager/tunedmanager.h
Added logging to dbus worker methods.
> Added logging to dbus worker methods

- src/lib/tunedmanager/tunedmanager.cpp
Enabled interactive authorization support to fix the "Interactive authentication required" dbus error.
> Enabled interactive authorization support

- src/app/main.cpp
- src/app/mainwindow/mainwindow.cpp
- src/app/mainwindow/mainwindow.h
- src/app/trayicon/trayicon.cpp
- src/app/trayicon/trayicon.h
- src/lib/appconstants/appconstants.h.in
- src/lib/notificationsmanager/dbusconverters.h
- src/lib/notificationsmanager/notificationsmanager.cpp
- src/lib/notificationsmanager/notificationsmanager.h
- src/lib/translationmanager/translationmanager.cpp
- src/lib/translationmanager/translationmanager.h
- src/lib/tunedmanager/tunedmanager.cpp
- src/lib/tunedmanager/tunedmanager.h
- src/lib/tunedtypes/tunedtypes.cpp
- src/lib/tunedtypes/tunedtypes.h
Updated the inline documentation for various source files.
> Inline documentation update

- src/app/main.cpp
- src/app/mainwindow/mainwindow.cpp
- src/app/mainwindow/mainwindow.h
- src/app/trayicon/trayicon.cpp
- src/app/trayicon/trayicon.h
- src/lib/notificationsmanager/dbusconverters.h
- src/lib/notificationsmanager/notificationsmanager.cpp
- src/lib/notificationsmanager/notificationsmanager.h
- src/lib/translationmanager/translationmanager.cpp
- src/lib/translationmanager/translationmanager.h
- src/lib/tunedmanager/tunedmanager.cpp
- src/lib/tunedmanager/tunedmanager.h
- src/lib/tunedtypes/tunedtypes.cpp
- src/lib/tunedtypes/tunedtypes.h
Reorganized includes in various source files.
> Includes reorganization

- src/app/mainwindow/mainwindow.cpp
- src/app/mainwindow/mainwindow.h
Implemented automatic profile switching in Widget mode.
> Implemented automatic profile switching in Widget mode

- src/app/mainwindow/mainwindow.cpp
- src/app/mainwindow/mainwindow.h
- src/app/mainwindow/mainwindow.ui
Added "Auto-select profile" feature to Widget mode.
> Added "Auto-select profile" feature to Widget mode

- src/app/trayicon/trayicon.cpp
- src/app/trayicon/trayicon.h
Improved the "Auto-select profile" feature in Applet mode.
> Improved the "Auto-select profile" feature in Applet mode

- src/app/mainwindow/mainwindow.h
- src/app/trayicon/trayicon.h
Updated the inline documentation for various methods.
> Updated the inline documentation

- src/app/mainwindow/mainwindow.cpp
- src/app/mainwindow/mainwindow.h
- src/lib/appconstants/appconstants.h.in
Fixed a crash on application shutdown in Widget mode.
> Fixed a crash on application shutdown in Widget mode

- assets/manpage/tuned-switcher.md.in
- src/app/trayicon/trayicon.cpp
- src/app/trayicon/trayicon.h
Fixed a crash on application shutdown in Applet mode.
> Fixed a crash on application shutdown in Applet mode

- src/app/mainwindow/mainwindow.cpp
- src/app/mainwindow/mainwindow.h
- src/app/mainwindow/mainwindow.ui
- src/app/trayicon/trayicon.cpp
Performed basic code unification between the Applet and the Widget code bases.
> Performed basic code unification

- CMakeLists.txt
- src/lib/logmanager/logmanager.cpp
- src/lib/logmanager/logmanager.h
- src/lib/tunedmanager/tunedmanager.cpp
Implemented log categories support.
> Implemented log categories support

- src/lib/logmanager/logmanager.cpp
- src/lib/logmanager/logmanager.h
- src/lib/tunedmanager/tunedmanager.cpp
Moved custom logging categories to a separate namespace.
> Moved custom logging categories to a separate namespace

- src/app/mainwindow/mainwindow.cpp
- src/app/mainwindow/mainwindow.h
Use a group to save/load Widget settings.
> Use a group to save/load Widget settings

- CMakeLists.txt
- src/lib/logcategories/logcategories.cpp
- src/lib/logcategories/logcategories.h
- src/lib/logmanager/logmanager.cpp
- src/lib/tunedmanager/tunedmanager.cpp
Renamed the logging categories namespace to better suit its purpose.
> Renamed namespace with logging categories

- assets/i18n/tuned-switcher_en.ts
- assets/i18n/tuned-switcher_ru.ts
- src/app/mainwindow/mainwindow.cpp
- src/app/trayicon/trayicon.cpp
Implemented the ability to show different messages on manual and automatic performance profile changes.
> Show different messages on profile changes

- assets/i18n/tuned-switcher_en.ts
- assets/i18n/tuned-switcher_ru.ts
- src/app/mainwindow/mainwindow.cpp
- src/app/trayicon/trayicon.cpp
> Updated various messages

- assets/metainfo/tuned-switcher.metainfo.xml.in
Updated the project metadata file.
> Updated the project metadata file

- src/app/mainwindow/mainwindow.cpp
- src/app/mainwindow/mainwindow.h
- src/app/trayicon/trayicon.cpp
- src/app/trayicon/trayicon.h
Marked various variables as const for better optimization.
> Marked various variables as const
